### ISSUE TITLE
Where's Select.java

### ISSUE THREAD

**Issue by GavinCT** [rzwitserloot/lombok.ast#9]
When I import this project, I see AstVisitor has a method visitSelect, but I can't see Select.java in this package. Please help me. Thank you.

**Comment by rspilker** [comment]
It is generated by the template processor. You need to check your eclipse project settings. In Java Compiler/Annotation Processing, `Enable annotation processing` should be enabled as well as `Enable processing in editor`. On my machine the `Generated source directory` is set to `.apt_generated`. That directory is also on the `Java Build Path`.

Did you run `ant eclipse`?
